In [2]:
import torch

In [3]:
torch.cuda.is_available?

In [4]:
torch.cuda?

In [5]:
print(torch.cuda.is_available())

False


In [6]:
torch?

In [7]:
a = torch.ones(8)

In [8]:
a

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
a[5]

tensor(1.)

In [10]:
float(a[3])

1.0

In [11]:
a[1] = 2

In [12]:
a[2] = 2.0

In [13]:
a[2]

tensor(2.)

In [14]:
a[2] = 3

In [15]:
a[2]

tensor(3.)

In [16]:
a.shape

torch.Size([8])

In [17]:
b = torch.tensor([])

In [18]:
b

tensor([])

## Data Types

In [19]:
torch.zeros(10, 2, dtype=torch.double)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [20]:
torch.zeros(10, 2, dtype=torch.short)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int16)

In [21]:
torch.zeros(10, 2).double()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [22]:
torch.zeros(10, 2).to(torch.short)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int16)

### Indexing

In [29]:
points = torch.randn(10, 2)

In [48]:
points

tensor([[-0.3983, -0.5612],
        [-0.2462,  0.0036],
        [ 0.2639, -0.5615],
        [-0.5329, -1.2170],
        [ 0.2336,  0.7302],
        [-1.0529, -1.3463],
        [-2.0209, -0.5505],
        [ 1.2504,  0.1170],
        [-0.2173, -0.8366],
        [-0.5050,  1.3411]])

In [30]:
points[0]

tensor([-0.3983, -0.5612])

In [31]:
points[1:]

tensor([[-0.2462,  0.0036],
        [ 0.2639, -0.5615],
        [-0.5329, -1.2170],
        [ 0.2336,  0.7302],
        [-1.0529, -1.3463],
        [-2.0209, -0.5505],
        [ 1.2504,  0.1170],
        [-0.2173, -0.8366],
        [-0.5050,  1.3411]])

In [33]:
points[1:, 1]

tensor([ 0.0036, -0.5615, -1.2170,  0.7302, -1.3463, -0.5505,  0.1170, -0.8366,
         1.3411])

In [45]:
points[(0, 2), (0, 1)]

tensor([-0.3983, -0.5615])

### NumPy interop

In [46]:
points_np = points.numpy()

In [47]:
points_np

array([[-0.398341  , -0.5611648 ],
       [-0.24618557,  0.00359378],
       [ 0.26392305, -0.5614785 ],
       [-0.53292483, -1.2170285 ],
       [ 0.2336356 ,  0.7302144 ],
       [-1.0529026 , -1.3463128 ],
       [-2.0209374 , -0.55051243],
       [ 1.250351  ,  0.11700475],
       [-0.21728557, -0.8365746 ],
       [-0.5049972 ,  1.3411402 ]], dtype=float32)

In [49]:
points = torch.from_numpy(points_np)

In [50]:
points

tensor([[-0.3983, -0.5612],
        [-0.2462,  0.0036],
        [ 0.2639, -0.5615],
        [-0.5329, -1.2170],
        [ 0.2336,  0.7302],
        [-1.0529, -1.3463],
        [-2.0209, -0.5505],
        [ 1.2504,  0.1170],
        [-0.2173, -0.8366],
        [-0.5050,  1.3411]])

In [51]:
!ls

Untitled.html  datasets  deep-learning-with-pytorch.ipynb  storage


### Storage

In [58]:
import os

In [59]:
!ls

Untitled.html  datasets  deep-learning-with-pytorch.ipynb  storage


In [60]:
os.makedirs('../storage/deep-learning-with-python')

In [63]:
!ls storage/deep-learning-with-python

In [64]:
stored = torch.randn(10, 4)

In [65]:
stored

tensor([[ 0.8551,  0.5595, -0.2002,  1.4217],
        [ 0.7213,  0.3824, -1.1189, -0.0939],
        [-0.9313,  0.5158,  0.8866, -1.1566],
        [-0.4142, -0.5651, -0.0991, -0.8455],
        [ 1.1006,  1.7481,  1.1111, -0.7036],
        [-0.0643, -0.7077, -0.2569,  0.0040],
        [ 0.8501,  0.7306,  0.8400, -0.8831],
        [-0.4087, -1.4792, -0.5180,  1.0018],
        [-0.4672, -1.1176, -1.2807, -0.3133],
        [ 0.4508, -1.0619,  0.1331,  0.3835]])

In [66]:
torch.save(stored, '../storage/deep-learning-with-python/stored.t')

In [67]:
!ls storage/deep-learning-with-python

stored.t


In [68]:
opened = torch.load('../storage/deep-learning-with-python/stored.t')

In [69]:
opened

tensor([[ 0.8551,  0.5595, -0.2002,  1.4217],
        [ 0.7213,  0.3824, -1.1189, -0.0939],
        [-0.9313,  0.5158,  0.8866, -1.1566],
        [-0.4142, -0.5651, -0.0991, -0.8455],
        [ 1.1006,  1.7481,  1.1111, -0.7036],
        [-0.0643, -0.7077, -0.2569,  0.0040],
        [ 0.8501,  0.7306,  0.8400, -0.8831],
        [-0.4087, -1.4792, -0.5180,  1.0018],
        [-0.4672, -1.1176, -1.2807, -0.3133],
        [ 0.4508, -1.0619,  0.1331,  0.3835]])

In [76]:
opened.device

device(type='cpu')

In [77]:
opened_gpu = opened.cuda()

AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

### Tensor API

In [78]:
tensor = torch.randn(10, 4)

In [83]:
tensor_transposed = tensor.transpose(0, 1)

In [86]:
tensor_transposed = torch.transpose(tensor, 0, 1)

In [91]:
a = torch.ones(4, 2)

In [92]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [93]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [94]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [95]:
b = torch.ones(4, 2)

In [96]:
a + b

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [97]:
b + torch.randn(4, 2)

tensor([[ 1.9981,  0.7300],
        [ 2.1513,  1.0838],
        [ 0.9821,  0.9365],
        [-0.0557,  0.5842]])

In [99]:
from_list = torch.tensor(list(range(9)))

In [100]:
from_list

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
from_list.size()

torch.Size([9])

In [104]:
from_list.stride()

(1,)

In [105]:
from_list.storage_offset()

0

In [106]:
a = from_list.view(3,3)

In [107]:
a[1,1]

tensor(4)

In [115]:
a.storage_offset()

0

In [110]:
b = a[1:,1:]

In [111]:
b

tensor([[4, 5],
        [7, 8]])

In [112]:
b.size()

torch.Size([2, 2])

In [113]:
b.stride()

(3, 1)

In [114]:
b.storage_offset()

4

In [117]:
c = torch.randn(10, 3)

In [118]:
c

tensor([[ 0.3980,  1.2764,  0.9873],
        [-0.1022, -0.7997,  1.5240],
        [ 0.3916, -0.0084, -1.0631],
        [-0.3227, -0.1960,  0.4695],
        [ 0.7452, -0.2487, -0.0989],
        [-0.2141,  0.8701,  0.6088],
        [-0.4642, -0.7774, -0.3066],
        [ 0.2661, -0.8253, -0.8631],
        [ 2.5250,  1.4208,  0.7714],
        [ 0.1043, -0.5747,  1.1583]])

In [119]:
c.tan()

tensor([[ 4.2047e-01,  3.2981e+00,  1.5148e+00],
        [-1.0258e-01, -1.0291e+00,  2.1345e+01],
        [ 4.1291e-01, -8.3967e-03, -1.7976e+00],
        [-3.3439e-01, -1.9860e-01,  5.0736e-01],
        [ 9.2270e-01, -2.5400e-01, -9.9213e-02],
        [-2.1743e-01,  1.1855e+00,  6.9720e-01],
        [-5.0075e-01, -9.8418e-01, -3.1660e-01],
        [ 2.7252e-01, -1.0832e+00, -1.1688e+00],
        [-7.0881e-01,  6.6188e+00,  9.7229e-01],
        [ 1.0465e-01, -6.4766e-01,  2.2850e+00]])

In [120]:
torch.tan(c)

tensor([[ 4.2047e-01,  3.2981e+00,  1.5148e+00],
        [-1.0258e-01, -1.0291e+00,  2.1345e+01],
        [ 4.1291e-01, -8.3967e-03, -1.7976e+00],
        [-3.3439e-01, -1.9860e-01,  5.0736e-01],
        [ 9.2270e-01, -2.5400e-01, -9.9213e-02],
        [-2.1743e-01,  1.1855e+00,  6.9720e-01],
        [-5.0075e-01, -9.8418e-01, -3.1660e-01],
        [ 2.7252e-01, -1.0832e+00, -1.1688e+00],
        [-7.0881e-01,  6.6188e+00,  9.7229e-01],
        [ 1.0465e-01, -6.4766e-01,  2.2850e+00]])

In [ ]:
c.sqrt_()